# Copyright 2025 Schelling Point Labs Inc
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "ah-rest-client-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
ah-client-api = { workspace = true }
ah-test-scenarios = { workspace = true }
ah-rest-api-contract = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true }
