# Copyright 2025 Schelling Point Labs Inc
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "sandbox-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
nix = { version = "0.27", features = [
  "sched",
  "mount",
  "user",
  "process",
  "fs",
] }
sandbox-cgroups = { workspace = true, optional = true }
sandbox-seccomp = { workspace = true, optional = true }
sandbox-net = { workspace = true, optional = true }
sandbox-devices = { workspace = true, optional = true }
sandbox-fs = { workspace = true }
sandbox-proto = { workspace = true }

[features]
default = ["cgroups", "seccomp", "net", "devices"]
cgroups = ["sandbox-cgroups"]
seccomp = ["sandbox-seccomp"]
net = ["sandbox-net"]
devices = ["sandbox-devices"]

[dev-dependencies]
tempfile = { workspace = true }
