# Copyright 2025 Schelling Point Labs Inc
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "sandbox-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
nix = { version = "0.27", features = [
  "sched",
  "mount",
  "user",
  "process",
  "fs",
] }
sandbox-cgroups = { path = "../sandbox-cgroups", optional = true }
sandbox-seccomp = { path = "../sandbox-seccomp", optional = true }
sandbox-net = { path = "../sandbox-net", optional = true }
sandbox-devices = { path = "../sandbox-devices", optional = true }
sandbox-fs = { path = "../sandbox-fs" }
sandbox-proto = { path = "../sandbox-proto" }

[features]
default = ["cgroups", "seccomp"]
cgroups = ["sandbox-cgroups"]
seccomp = ["sandbox-seccomp"]
net = ["sandbox-net"]
devices = ["sandbox-devices"]

[dev-dependencies]
ah-test-utils = { workspace = true }
tempfile = { workspace = true }
